### PR TITLE
Please review the part 5 assignment

### PR DESCRIPTION
**Pull request by jayjaykai**
張智凱
http://54.79.121.157:8000/
http://54.79.121.157:8000/attraction/10
http://54.79.121.157:8000/booking

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Cannot booking a trip. Your API is broken.

**Comment by jayjaykai** [comment]
Fixed the issue, please review it again!

張智凱
http://54.79.121.157:8000/
http://54.79.121.157:8000/attraction/10
http://54.79.121.157:8000/booking

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Layout width exceeds screen width in middle size of devices.
- Attraction image in the booking page should extend to full width in mobile layout.
- Your pages always call User Auth API twice after loading.
未命名-2

**Comment by jayjaykai** [comment]
Fixed all the issues, please review it again!

張智凱
http://54.79.121.157:8000/
http://54.79.121.157:8000/attraction/10
http://54.79.121.157:8000/booking

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
